Feature/abstract module and client
fixstars/arachne-runtime pull request #4
Opened 2022-05-20 03:32 UTC by ry3s

* Use `RuntimeModuleBase` as a base class for `RpcRuntimeModule` (old name: `RuntimeClient`)
* Add `get_input_details` and `get_output_details` to RPC 
* Change the return value of `get_input_details` and `get_output_details` 
  * `List[ { name:string, dtype: string, shape: List[int] } ]`
* Update test files related to above changes

2022-05-26 04:21 UTC, tk1012 requested changes

2022-05-26 04:21 UTC, tk1012 commented on python/arachne_runtime/__init__.py
> +from arachne_runtime.rpc.client.client import RpcRuntimeModule
Unused import

2022-05-26 04:21 UTC, tk1012 commented on python/arachne_runtime/__init__.py
> +from arachne_runtime.rpc.server import create_channel
Unused import

2022-05-27 02:03 UTC, ry3s commented on python/arachne_runtime/__init__.py
> +from arachne_runtime.rpc.server import create_channel
Deleted.

2022-05-27 02:04 UTC, ry3s commented on python/arachne_runtime/__init__.py
> +from arachne_runtime.rpc.client.client import RpcRuntimeModule
`import arachne_runtime.rpc` is needed to register `RpcRuntimeModule` to the factory

2022-05-27 02:39 UTC, tk1012 approved these changes

2022-05-27 02:40 UTC, merged